import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const resendApiKey = process.env.RESEND_API_KEY || '';
const resendFromEmail = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';
const clientEmail = process.env.CLIENT_EMAIL || '';

const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;
const resend = resendApiKey ? new Resend(resendApiKey) : null;

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { name, email, telegramUsername, projectType, message } = body;

    // Validate required fields
    if (!name || !email || !projectType || !message) {
      return NextResponse.json(
        { error: 'All required fields must be filled' },
        { status: 400 }
      );
    }

    // Validate email format
    if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(email)) {
      return NextResponse.json(
        { error: 'Invalid email address' },
        { status: 400 }
      );
    }

    // Save to Supabase if configured
    if (supabase) {
      const { error: dbError } = await supabase
        .from('contact_submissions')
        .insert([
          {
            name,
            email,
            telegram_username: telegramUsername || null,
            project_type: projectType,
            message,
            // created_at and updated_at are auto-generated by the database
          },
        ]);

      if (dbError) {
        console.error('Supabase error:', dbError);
        return NextResponse.json(
          { error: 'Failed to save submission to database', details: dbError.message },
          { status: 500 }
        );
      }
    }

    // Send email via Resend if configured
    if (resend) {
      try {
        await resend.emails.send({
          from: resendFromEmail,
          to: clientEmail,
          subject: ` Form Submission: from ${name}`,
          html: `
            <div style="font-family: Verdana, sans-serif; max-width: 640px; margin: 0 auto; padding: 20px; background:#fafafa;">
  <h2 style="
    color:#3B1A6E; 
    border-bottom: 2px solid #3B1A6E; 
    padding-bottom: 10px;
    margin-top: 0;
  ">
    Contact Form Submission
  </h2>

  <div style="
    background-color: #ffffff; 
    padding: 20px; 
    border-radius: 8px; 
    margin: 20px 0; 
    border: 1px solid #e5e7eb;
  ">
    <p><strong style="color:#111827;">Name:</strong> <span style="color:#4b5563;">${name}</span></p>
    <p><strong style="color:#111827;">Email:</strong> <span style="color:#4b5563;">${email}</span></p>

    ${telegramUsername ? `
      <p><strong style="color:#111827;">Telegram Username:</strong> 
      <span style="color:#4b5563;">${telegramUsername}</span></p>` 
    : ''}

    <p><strong style="color:#111827;">Project Type:</strong> 
    <span style="color:#4b5563;">${projectType}</span></p>
  </div>

  <div style="
    background-color: #ffffff; 
    padding: 20px; 
    border-radius: 8px; 
    border-left: 4px solid #8B5CF6; 
    border: 1px solid #e5e7eb;
  ">
    <p style="margin-top: 0;"><strong style="color:#111827;">Message:</strong></p>
    <p style="color:#4b5563; line-height:1.6; white-space:pre-wrap;">${message}</p>
  </div>

  <p style="color:#9ca3af; font-size:12px; margin-top:20px; text-align:center;">
    This email was sent from Incurify.
  </p>

</div>


          `,
        });
      } catch (emailError) {
        console.error('Resend error:', emailError);
        // Log error but don't fail the request if email fails
      }
    }

    return NextResponse.json(
      { message: 'Contact form submitted successfully' },
      { status: 200 }
    );
  } catch (error) {
    console.error('Error processing contact form:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
