import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const resendApiKey = process.env.RESEND_API_KEY || '';
const resendFromEmail = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';

const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;
const resend = resendApiKey ? new Resend(resendApiKey) : null;

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { email } = body;

    // Validate email
    if (!email || !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(email)) {
      return NextResponse.json(
        { error: 'Valid email is required' },
        { status: 400 }
      );
    }

    // Save to Supabase if configured
    if (supabase) {
      // Check if email already exists
      const { data: existing, error: checkError } = await supabase
        .from('newsletter_subscriptions')
        .select('id, email, is_active')
        .eq('email', email)
        .single();

      if (checkError && checkError.code !== 'PGRST116') {
        // PGRST116 is "not found" error, which is fine
        console.error('Error checking existing subscription:', checkError);
      }

      if (existing) {
        // If email exists and is active, return success
        if (existing.is_active) {
          return NextResponse.json(
            { message: 'Email already subscribed' },
            { status: 200 }
          );
        }

        // If email exists but is inactive, reactivate it
        const { error: updateError } = await supabase
          .from('newsletter_subscriptions')
          .update({
            is_active: true,
            subscribed_at: new Date().toISOString(),
            unsubscribed_at: null,
            // updated_at is auto-updated by trigger
          })
          .eq('email', email);

        if (updateError) {
          console.error('Error reactivating subscription:', updateError);
          return NextResponse.json(
            { error: 'Failed to reactivate subscription', details: updateError.message },
            { status: 500 }
          );
        }
      } else {
        // Insert new subscription
        const { error: dbError } = await supabase
          .from('newsletter_subscriptions')
          .insert([
            {
              email,
              is_active: true,
              // subscribed_at is auto-generated by the database
            },
          ]);

        if (dbError) {
          console.error('Supabase error:', dbError);
          return NextResponse.json(
            { error: 'Failed to save subscription', details: dbError.message },
            { status: 500 }
          );
        }
      }
    }

    // Send confirmation email via Resend if configured
    if (resend) {
      try {
        await resend.emails.send({
          from: resendFromEmail,
          to: email,
          subject: 'Welcome to Web3Agency Newsletter!',
          html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
              <h2 style="color: #8B5CF6; border-bottom: 2px solid #06B6D4; padding-bottom: 10px;">
                Thank you for subscribing!
              </h2>
              <div style="background-color: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <p style="color: #333; line-height: 1.6;">
                  You've successfully subscribed to the Web3Agency newsletter. Stay tuned for the latest updates on Web3, blockchain, and decentralized technologies.
                </p>
                <p style="color: #333; line-height: 1.6; margin-top: 15px;">
                  We'll keep you informed about:
                </p>
                <ul style="color: #666; line-height: 1.8; margin-left: 20px;">
                  <li>Latest Web3 trends and innovations</li>
                  <li>Blockchain development insights</li>
                  <li>Smart contract best practices</li>
                  <li>Industry news and updates</li>
                </ul>
              </div>
              <p style="color: #999; font-size: 12px; margin-top: 20px;">
                Best regards,<br>
                <strong style="color: #8B5CF6;">The Web3Agency Team</strong>
              </p>
            </div>
          `,
        });
      } catch (emailError) {
        console.error('Resend error:', emailError);
        // Log error but don't fail the request if email fails
      }
    }

    return NextResponse.json(
      { message: 'Successfully subscribed to newsletter' },
      { status: 200 }
    );
  } catch (error) {
    console.error('Error processing newsletter subscription:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
